2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_setup.py:_flush():67] Configure stats pid to 19940
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Administrator\.config\wandb\settings
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Administrator\Desktop\di725-term-project\di725-project\notebooks\wandb\settings
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_init.py:setup_run_log_directory():662] Logging user logs to C:\Users\Administrator\Desktop\di725-term-project\di725-project\notebooks\wandb\run-20250420_200454-6241vp7d\logs\debug.log
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to C:\Users\Administrator\Desktop\di725-term-project\di725-project\notebooks\wandb\run-20250420_200454-6241vp7d\logs\debug-internal.log
2025-04-20 20:04:54,179 INFO    MainThread:19940 [wandb_init.py:monkeypatch_ipython():581] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B59E7A62F0>
2025-04-20 20:04:54,180 INFO    MainThread:19940 [wandb_init.py:init():781] calling init triggers
2025-04-20 20:04:54,180 INFO    MainThread:19940 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-20 20:04:54,180 INFO    MainThread:19940 [wandb_init.py:init():809] starting backend
2025-04-20 20:04:54,180 INFO    MainThread:19940 [wandb_init.py:init():813] sending inform_init request
2025-04-20 20:04:54,190 INFO    MainThread:19940 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-20 20:04:54,190 INFO    MainThread:19940 [wandb_init.py:init():823] backend started and connected
2025-04-20 20:04:54,193 INFO    MainThread:19940 [wandb_run.py:_label_probe_notebook():1267] probe notebook
2025-04-20 20:04:54,195 INFO    MainThread:19940 [wandb_run.py:_label_probe_notebook():1277] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-20 20:04:54,195 INFO    MainThread:19940 [wandb_init.py:init():915] updated telemetry
2025-04-20 20:04:54,364 INFO    MainThread:19940 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-20 20:04:54,882 INFO    MainThread:19940 [wandb_init.py:init():1014] starting run threads in backend
2025-04-20 20:04:55,281 INFO    MainThread:19940 [wandb_run.py:_console_start():2454] atexit reg
2025-04-20 20:04:55,281 INFO    MainThread:19940 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-20 20:04:55,282 INFO    MainThread:19940 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-20 20:04:55,282 INFO    MainThread:19940 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-20 20:04:55,285 INFO    MainThread:19940 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-20 20:04:55,285 INFO    MainThread:19940 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-20 20:04:55,285 INFO    MainThread:19940 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-20 20:05:12,307 INFO    MainThread:19940 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-20 20:05:12,309 INFO    MainThread:19940 [wandb_run.py:_config_callback():1327] config_cb None None {'task': 'EDA', 'script': 'phase1_eda.ipynb', 'dataset': 'RISC', 'date': '2025-04-20'}
2025-04-20 20:05:13,383 INFO    MainThread:19940 [jupyter.py:save_ipynb():384] [no run ID] not saving jupyter notebook
2025-04-20 20:05:13,383 INFO    MainThread:19940 [wandb_init.py:_pause_backend():546] [no run ID] pausing backend
2025-04-20 20:05:40,604 INFO    MainThread:19940 [wandb_init.py:_resume_backend():551] [no run ID] resuming backend
2025-04-20 20:05:40,606 INFO    MainThread:19940 [wandb_run.py:_config_callback():1327] config_cb None None {'task': 'EDA', 'script': 'phase1_eda.ipynb', 'dataset': 'RISC', 'date': '2025-04-20'}
